version: "3.7"

services:
    database_postgres:
        image: postgres
        container_name: database_postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=docker
        volumes:
            - pgdata:/data/postgres
        extra_hosts:
            - "host.docker.internal:172.17.0.1"

    app:
        build: .
        command: yarn dev
        container_name: node_service
        ports:
            - "3000:5050"
            - "5000:8080"
        volumes:
            - .:/usr/app
            - /usr/app/node_modules
        depends_on:
            - database_postgres
        environment:
          - DB_URL=postgresql://docker:docker@database_postgres:5432/docker


volumes:
    pgdata:
        driver: local
