version: "3.7"

services:
    database_postgres:
        image: postgres
        container_name: database_postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=docker
        volumes:
            - pgdata:/data/postgres
        extra_hosts:
            - "host.docker.internal:172.17.0.1"

    redis:
        image: redis
        container_name: database_redis
        command: redis-server --requirepass docker
        ports:
            - "6379:6379"
        environment:
          - REDIS_REPLICATION_MODE=master
        restart: always
        volumes:
          - redis_data:/data/redis

    mongo:
        image: mongo
        container_name: database_mongo
        restart: always
        ports:
          - ${MONGO_PORT}:27017
        environment:
            - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

    mongo-express:
        image: mongo-express
        container_name: mongo_express
        restart: always
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
            - ME_CONFIG_MONGODB_URL=mongodb://mongo:${MONGO_PORT}/${MONGO_DATABASE}

    app:
        build: .
        command: yarn dev
        container_name: node_service
        ports:
            - "3000:5050"
            - "5000:8080"
        volumes:
            - .:/usr/app
            - /usr/app/node_modules
        depends_on:
            - database_postgres
            - redis
            - mongo
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REDIS_PASSWORD=docker
            - DB_URL=postgresql://docker:docker@database_postgres:5432/docker

volumes:
    pgdata:
        driver: local
    redis_data:
        driver: local
