version: "3.7"

services:
    app:
        build: .
        command: yarn dev
        container_name: node_service
        ports:
            - "3000:5050"
            - "5000:8080"
        volumes:
            - .:/usr/app
        restart: always

