version: "3.7"

services:
    database_postgres:
        image: postgres
        container_name: database_postgres
        restart: always
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - pgdata:/data/postgres
        extra_hosts:
            - "host.docker.internal:172.17.0.1"

    redis:
        image: redis
        container_name: database_redis
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - "${REDIS_PORT}:${REDIS_PORT}"
        environment:
          - REDIS_REPLICATION_MODE=${REDIS_REPLICATION_MODE}
        restart: always
        volumes:
          - redis_data:/data/redis

    mongo:
        image: mongo
        container_name: database_mongo
        restart: always
        ports:
          - ${MONGO_PORT}:${MONGO_PORT}
        environment:
            - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

    app:
        build: .
        restart: always
        command: ["yarn", "dev"]
        container_name: node_service
        ports:
            - "3000:${PORT_TLS}"
            - "5000:${PORT}"
        volumes:
            - .:/usr/app
            - /usr/app/node_modules
        depends_on:
            - database_postgres
            - redis
            - mongo
        environment:
            - DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database_postgres:${POSTGRES_PORT}/${POSTGRES_DB}
            - MONGO_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}/${MONGO_DATABASE}
            - REDIS_URL=redis://default:${REDIS_PASSWORD}@redis:${REDIS_PORT}
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "5"

volumes:
    pgdata:
        driver: local
    redis_data:
        driver: local
