version: "3.7"

services:
    database_postgres:
        image: postgres
        container_name: database_postgres
        restart: always
        ports:
          - "5432:5432"
        environment:
          - POSTGRES_USER=docker
          - POSTGRES_PASSWORD=docker
          - POSTGRES_DB=docker
        volumes:
            - pgdata:/data/postgres

    app:
        build: .
        command: yarn dev
        container_name: node_service
        ports:
            - "3000:5050"
            - "5000:8080"
        volumes:
            - .:/usr/app



volumes:
    pgdata:
        driver: local
